<a href="https://colab.research.google.com/github/Thiruvikramchoudry/Chatbot-Pulse/blob/master/SkinVsNonskin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv('Skin_NonSkin.txt', sep='\t')

df

B    G    R  value
0       74   85  123    1.0
1       73   84  122    1.0
2       72   83  121    1.0
3       70   81  119    1.0
4       70   81  119    1.0
...    ...  ...  ...    ...
72712  131  141  151    2.0
72713  128  138  148    2.0
72714  124  134  144    2.0
72715  122  133  141    2.0
72716  121  132    1    NaN

[72717 rows x 4 columns]

In [3]:
df.head

<bound method NDFrame.head of          B    G    R  value
0       74   85  123    1.0
1       73   84  122    1.0
2       72   83  121    1.0
3       70   81  119    1.0
4       70   81  119    1.0
...    ...  ...  ...    ...
72712  131  141  151    2.0
72713  128  138  148    2.0
72714  124  134  144    2.0
72715  122  133  141    2.0
72716  121  132    1    NaN

[72717 rows x 4 columns]>

In [4]:
df.isnull().sum()

B        0
G        0
R        0
value    1
dtype: int64

In [5]:
df.dropna(inplace=True)

In [6]:
df.isnull().sum()

B        0
G        0
R        0
value    0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X = df[['R', 'G', 'B']]
y = df['value']

print(X)

         R    G    B
0      123   85   74
1      122   84   73
2      121   83   72
3      119   81   70
4      119   81   70
...    ...  ...  ...
72711  152  144  133
72712  151  141  131
72713  148  138  128
72714  144  134  124
72715  141  133  122

[72716 rows x 3 columns]


In [8]:
from sklearn.ensemble import RandomForestClassifier

# Create the  model
model = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0)

# Train the model on the training data
model.fit(X, y)

RandomForestClassifier(max_depth=2, random_state=0)

In [9]:
import joblib

# Save the model to a file
model_filename = 'Skin_NonSkin_model.pkl'
joblib.dump(model, model_filename)
loaded_model = joblib.load(model_filename)

In [10]:
from google.colab import files

files.download('Skin_NonSkin_model.pkl')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [12]:
from PIL import Image
import numpy as np

def resize_image(image_path, target_size=(28, 28)):
    # Open the image using Pillow
    img = Image.open(image_path)

    # Resize the image to the target size (28x28 pixels)
    img_resized = img.resize(target_size, Image.ANTIALIAS)

    return img_resized

def image_to_rgb_grid(image_path, target_size=(28, 28)):
    # Resize the image
    img_resized = resize_image(image_path, target_size)

    # Convert the image to a NumPy array
    img_array = np.array(img_resized)

    # Normalize the pixel values to the range [0, 1]
    img_array = img_array

    return img_array

# Replace 'path/to/your/image.jpg' with the actual path to your image file
image_path = 'ISIC_0024306.jpg'

# Convert the image to a 28x28 grid of RGB values
rgb_grid = image_to_rgb_grid(image_path)

# Print the shape of the RGB grid (should be (28, 28, 3) for RGB images)
print(rgb_grid)



[[[229 125 123]
  [231 124 128]
  [233 130 138]
  ...
  [235 141 153]
  [232 139 150]
  [227 129 144]]

 [[231 130 137]
  [234 131 140]
  [235 134 146]
  ...
  [232 135 149]
  [229 132 148]
  [228 131 147]]

 [[231 135 144]
  [234 133 145]
  [237 135 152]
  ...
  [229 132 147]
  [229 136 149]
  [231 139 147]]

 ...

 [[217 120 115]
  [224 133 133]
  [229 140 146]
  ...
  [221 136 128]
  [216 133 118]
  [217 132 120]]

 [[219 126 122]
  [225 136 138]
  [226 137 138]
  ...
  [225 144 135]
  [221 141 128]
  [221 142 131]]

 [[218 126 124]
  [224 136 138]
  [228 139 143]
  ...
  [229 151 142]
  [225 149 138]
  [224 148 136]]]


In [15]:
skin_count=0;non_skin_count=0
for x in rgb_grid:
  predictions = model.predict(x)
  for i, prediction in enumerate(predictions):
    if prediction==1:
      skin_count+=1
    else:
      non_skin_count+=1
print(skin_count,non_skin_count)


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X

689 95


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [18]:
predicted_skin_percentage=skin_count*100/(skin_count+non_skin_count)
print("The Predicted Skin Percentage",'%.2f' % predicted_skin_percentage,"%")

The Predicted Skin Percentage 87.88 %
